/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Controllers.EmpresaJpaController;
import Controllers.PersonaJpaController;
import Entitys.Empresa;
import Entitys.Persona;
import Views.Settings.TableColumnAdjuster;
import java.awt.Component;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Gabriel
 */
public class DlgEmpresaBusqueda extends javax.swing.JDialog {
    
     List<Empresa> listaEmpresa;
     private final JInternalFrame padre;
     Component formulariopadre;
    /**
     * Creates new form DlgProveedorBusqueda
     * @param componente
     */
    public DlgEmpresaBusqueda(Component componente) {
        super(JOptionPane.getFrameForComponent(componente), true);
        padre = (JInternalFrame) componente;
        initComponents();
        this.formulariopadre = componente;
        this.setLocationRelativeTo(componente);
        this.presentarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Representante:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableEmpresasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpresas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEmpresasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpresasMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            if(this.padre instanceof frmMantEmpresas){
                ((frmMantEmpresas) padre).empresa = listaEmpresa.get(jTableEmpresas.getSelectedRow());
                listaEmpresa.remove(jTableEmpresas.getSelectedRow());
                this.dispose();
            }else if(this.padre instanceof frmMantCreditoPersonas){
                ((frmMantCreditoPersonas) padre).empresa = listaEmpresa.get(jTableEmpresas.getSelectedRow());
                listaEmpresa.remove(jTableEmpresas.getSelectedRow());
                this.dispose();
            }else{
                this.dispose();
            }        
        }
    }//GEN-LAST:event_jTableEmpresasMouseReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
          if (!txtEmpresa.getText().equals("")) {
            listaEmpresa.clear();
            List<Empresa> lista = controladorEmpresa.buscarXPatron(txtEmpresa.getText());
            for(Empresa lista1 : lista){listaEmpresa.add(lista1);}           
        } else {
            this.presentarDatos();
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgProveedorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgProveedorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgProveedorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgProveedorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgProveedorBusqueda dialog = new DlgProveedorBusqueda(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresas;
    private javax.swing.JTextField txtEmpresa;
    // End of variables declaration//GEN-END:variables
    EmpresaJpaController controladorEmpresa = new EmpresaJpaController();
    public void presentarDatos() {
        listaEmpresa = controladorEmpresa.buscarTodos();
        listaEmpresa = ObservableCollections.observableList(listaEmpresa);
        JTableBinding binding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, listaEmpresa, jTableEmpresas);
        BeanProperty bNombre = BeanProperty.create("nombre");    
        BeanProperty bDireccion = BeanProperty.create("direccion"); 
        BeanProperty bRuc = BeanProperty.create("ruc");       
        
        binding.addColumnBinding(bNombre).setColumnName("NOMBRE").setEditable(false);  
        binding.addColumnBinding(bDireccion).setColumnName("DIRECCION").setEditable(false);
        binding.addColumnBinding(bRuc).setColumnName("RUC").setEditable(false);
        
        binding.bind();
        this.setAnchoColumnas();    
    }  
    
    public void setAnchoColumnas(){        
        jTableEmpresas.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableEmpresas);
        tca.adjustColumns();        
    } 
}
