/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Controlador;
import Controllers.DetalleEmpresaJpaController;
import Controllers.EmpresaJpaController;
import Controllers.PersonaJpaController;
import Entitys.Detalleempresa;
import Entitys.Empresa;
import Entitys.Persona;
import Views.Settings.ClaseUtil;
import Views.Settings.TableColumnAdjuster;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author GabrielRD
 */
public class frmAsigancionIntegrantes extends javax.swing.JDialog {
    
   
    private List<Detalleempresa> listaPersonasFiltradas = new ArrayList<>();   
    private List<Detalleempresa> listaPersonasDetallexempresa = new ArrayList<>(); 
    private List<Detalleempresa> listaPersonasDetalleBackup = new ArrayList<>(); 
    Component formulariopadre;
    Empresa datosRecibidos;
    private int accion;  

    /**
     * Creates new form frmAsigancionIntegrantes
     */
//    public frmAsigancionIntegrantes(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//    }
    
    public frmAsigancionIntegrantes(Component componente, Empresa datosRecibidos) {
        super(JOptionPane.getFrameForComponent(componente), true);
        initComponents();
        this.formulariopadre = componente;
        this.setLocationRelativeTo(componente);
        this.datosRecibidos = datosRecibidos; 
        this.presentarDatos();
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtApellidos2 = new javax.swing.JTextField();
        txtDni2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonaN = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIntegrantes = new javax.swing.JTable();
        jButtonAñadir = new javax.swing.JButton();
        jPanelAcciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciondes de Busqueda"));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Dni-Ruc:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 80;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel2, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 146;
        gridBagConstraints.gridy = 0;
        jPanel1.add(btnBuscar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 75;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtApellidos2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 82;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtDni2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Prestamistas"));

        jTablePersonaN.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTablePersonaN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePersonaN);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Integrantes"));

        jTableIntegrantes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableIntegrantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableIntegrantes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonAñadir.setText("------>");
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jPanelAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanelAcciones.setPreferredSize(new java.awt.Dimension(159, 149));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccionesLayout = new javax.swing.GroupLayout(jPanelAcciones);
        jPanelAcciones.setLayout(jPanelAccionesLayout);
        jPanelAccionesLayout.setHorizontalGroup(
            jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccionesLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(74, 74, 74))
        );
        jPanelAccionesLayout.setVerticalGroup(
            jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jButtonEliminar.setText("<------");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Responsable :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAñadir)
                            .addComponent(jButtonEliminar)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButtonAñadir)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
//        if (!txtApellidos2.getText().equals("")) {
//            listaPersonasFiltradas.clear();
//            listaPersonasFiltradas.addAll(controladorPersona.buscarXPatron(txtApellidos2.getText().trim()));
//        }else if(!txtDni2.getText().equals("")){
//            listaPersonasFiltradas.clear();
//            listaPersonasFiltradas.addAll(controladorPersona.buscarXPatron(txtDni2.getText().trim()));
//        }else{
//            this.presentarDatos();
//        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:           
        if (listaPersonasDetallexempresa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Asignar un Integrante como Mínimo", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
              
            
            try {
                this.accion = Controlador.NUEVO; 
                automaticGuardado("DetallesNuevos");
                this.accion = Controlador.ELIMINAR; 
                automaticGuardado("DetallesEliminados");
                this.accion = Controlador.MODIFICAR;
            } catch (Exception ex) {
                Logger.getLogger(frmAsigancionIntegrantes.class.getName()).log(Level.SEVERE, null, ex);
            }            
           
            if (2 == Controlador.MODIFICAR) {
                if (ClaseUtil.dialogoConfirmar(this, this.accion)) {
                    ClaseUtil.mensajeExito(this, accion);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:          
        Detalleempresa odetalleempresa = new Detalleempresa();
        if (jTablePersonaN.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Integrante de la Tabla Prestamistas", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            odetalleempresa = this.listaPersonasFiltradas.get(jTablePersonaN.getSelectedRow());
            listaPersonasFiltradas.remove(jTablePersonaN.getSelectedRow()); // Se Quita por observable list     
            listaPersonasDetallexempresa.add(odetalleempresa);
        }
          
          
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       // TODO add your handling code here:
        if (jTableIntegrantes.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Integrante de la Tabla Integrantes", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            listaPersonasFiltradas.add(listaPersonasDetallexempresa.get(jTableIntegrantes.getSelectedRow()));
            this.listaPersonasDetallexempresa.remove(jTableIntegrantes.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAsigancionIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAsigancionIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAsigancionIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAsigancionIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                frmAsigancionIntegrantes dialog = new frmAsigancionIntegrantes();
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAcciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIntegrantes;
    private javax.swing.JTable jTablePersonaN;
    private javax.swing.JTextField txtApellidos2;
    private javax.swing.JTextField txtDni2;
    // End of variables declaration//GEN-END:variables

    EmpresaJpaController controladorEmpresa = new EmpresaJpaController();
    PersonaJpaController controladorPersona = new PersonaJpaController();
    DetalleEmpresaJpaController controladorDetalleEmpresa = new DetalleEmpresaJpaController();
 
    public void presentarDatos() { 
 
        this.calculoListaFiltrada(controladorDetalleEmpresa.buscarTodos());
        this.listaPersonasFiltradas = ObservableCollections.observableList(listaPersonasFiltradas);
        JTableBinding binding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, listaPersonasFiltradas, jTablePersonaN);       
        BeanProperty bNombres = BeanProperty.create("idPersona.nombres");
        BeanProperty bApellidos = BeanProperty.create("idPersona.apellidos");
        BeanProperty bNum_identificacion = BeanProperty.create("idPersona.dni");
        binding.addColumnBinding(bNombres).setColumnName("NOMBRES").setEditable(false);
        binding.addColumnBinding(bApellidos).setColumnName("APELLIDOS").setEditable(false);
        binding.addColumnBinding(bNum_identificacion).setColumnName("DNI").setEditable(false);
        binding.bind();        
        jLabel10.setText(this.datosRecibidos.getNombre());
        jLabel4.setText(this.datosRecibidos.getDniRepresentante().getApellidos()+" "+this.datosRecibidos.getDniRepresentante().getNombres());
        
        ///------- Presentamos integrantes ya registrados a la Empresa------///  
        List<Detalleempresa> listPersonxEmpresa = new ArrayList<>();
        listPersonxEmpresa = controladorDetalleEmpresa.integrantesXempresa(datosRecibidos);
        this.listaPersonasDetalleBackup = controladorDetalleEmpresa.integrantesXempresa(datosRecibidos);
        for (Detalleempresa listaPersonas : listPersonxEmpresa) {
            this.listaPersonasDetallexempresa.add(listaPersonas);
        }  
        this.listaPersonasDetallexempresa = ObservableCollections.observableList(listaPersonasDetallexempresa);
        JTableBinding binding2 = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ,listaPersonasDetallexempresa, jTableIntegrantes);        
        BeanProperty bNombres2 = BeanProperty.create("idPersona.nombres");
        BeanProperty bApellidos2 = BeanProperty.create("idPersona.apellidos");
        BeanProperty bNum_identificacion2 = BeanProperty.create("idPersona.dni");
        binding2.addColumnBinding(bNombres2).setColumnName("NOMBRES").setEditable(false);
        binding2.addColumnBinding(bApellidos2).setColumnName("APELLIDOS").setEditable(false);
        binding2.addColumnBinding(bNum_identificacion2).setColumnName("DNI").setEditable(false);
        binding2.bind();
        this.setAnchoColumnas();
    }

    public void setAnchoColumnas() {
        jTablePersonaN.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTablePersonaN);
        tca.adjustColumns();
        jTableIntegrantes.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumnAdjuster tca2 = new TableColumnAdjuster(jTableIntegrantes);
        tca2.adjustColumns();
    }
    
    public void calculoListaFiltrada(List<Detalleempresa> odetalleempresa) { 
        for(int i = 0; i < this.listaPersonasFiltradas.size(); i++) {listaPersonasFiltradas.remove(i);}
        List<Empresa> listEmpresas = controladorEmpresa.buscarTodos();
        List<Persona> listPersonas = controladorPersona.buscarTodos();         
        ///---Filtro No Mostrar al Representante---///
        for (Empresa listEmpresa : listEmpresas) {         
            for (int j = 0; j < listPersonas.size(); j++) {
                if (listEmpresa.getDniRepresentante().getDni() == listPersonas.get(j).getDni()) {
                    listPersonas.remove(j);
                }                
            }
        }         
        ///---Filtro de Personas que Ya estan Asignadas     
        for (Detalleempresa listaPersonasDetalle2 : odetalleempresa) { 
            for (int i=0; i<listPersonas.size(); i++) {
                if (listaPersonasDetalle2.getIdPersona().getDni().equals(listPersonas.get(i).getDni())) {
                    listPersonas.remove(i);
                }
            }
        }  
        ///--Creamos la Lista de Detalles
        for (Persona listPersona : listPersonas) {
            Detalleempresa odetalle = new Detalleempresa();
            odetalle.setIdEmpresa(datosRecibidos);
            odetalle.setIdPersona(listPersona);
            this.listaPersonasFiltradas.add(odetalle);
        }
                  
    }
    
    public void automaticGuardado(String tipoList) throws Exception {        
       switch (tipoList) {
           case "DetallesNuevos":
               this.controladorDetalleEmpresa.prepararCrear(); 
               for (Detalleempresa listDetalleOrden1 : listaPersonasDetallexempresa) {
                   if (listDetalleOrden1.getIdDetalleEmpresa() == null) {
                       controladorDetalleEmpresa.setSeleccionado(listDetalleOrden1);
                       controladorDetalleEmpresa.accion(this.accion);                       
                   }
               }
               break;          
            case "DetallesEliminados":
                for (Detalleempresa listDetalleOrden1 : listaPersonasDetallexempresa) {
                    for (int i = 0; i < listaPersonasDetalleBackup.size(); i++) {
                        if (Objects.equals(listaPersonasDetalleBackup.get(i).getIdPersona().getDni(), listDetalleOrden1.getIdPersona().getDni())) {
                            listaPersonasDetalleBackup.remove(i);                            
                        }
                    }
                }
                for (Detalleempresa  listDetalle1: listaPersonasDetalleBackup) {
                    controladorDetalleEmpresa.setSeleccionado(listDetalle1);
                    controladorDetalleEmpresa.accion(this.accion);                                     
                }
                break;
        }
    }
    
   
    
    
}
